/*
 * generated by Xtext 2.12.0
 */
package br.com.kerubin.dsl.mkl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import br.com.kerubin.dsl.mkl.model.DomainModel

@RunWith(XtextRunner)
@InjectWith(MklInjectorProvider)
class MklParsingTest {
	@Inject
	ParseHelper<DomainModel> parseHelper
	
	@Test
	def void loadModel() {
		/*val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)*/
	}
}
