/*
 * generated by Xtext 2.12.0
 */
package br.com.kerubin.dsl.mkl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MklRuntimeModule extends AbstractMklRuntimeModule {
}
