/*
 * generated by Xtext 2.12.0
 */
package br.com.kerubin.dsl.mkl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MklStandaloneSetup extends MklStandaloneSetupGenerated {

	def static void doSetup() {
		new MklStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
