/*
 * generated by Xtext 2.12.0
 */
package br.com.kerubin.dsl.mkl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class MklScopeProvider extends AbstractMklScopeProvider {

}
