/*
 * generated by Xtext 2.12.0
 */
package br.com.kerubin.dsl.mkl.ide

import br.com.kerubin.dsl.mkl.MklRuntimeModule
import br.com.kerubin.dsl.mkl.MklStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MklIdeSetup extends MklStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MklRuntimeModule, new MklIdeModule))
	}
	
}
